version: '3.10'

services:
    transaction-app-postgresql:
        container_name: transaction-app-postgresql
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: transaction-appdb
        ports:
            - "5434:5432"
        volumes:
            - ./dev/postgresql/transaction-app:/var/lib/postgresql/data

    transaction-app-fastapi:
        container_name: transaction-app-fastapi
        restart: always
        build:
            context: .
            dockerfile: ./src/Dockerfile
        command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 
            # variables
            #        env_file:
            #            - ./dev/.env
        environment:
            DOCKER: "1"
            DATABASE_URL: "postgresql://postgres:postgres@transaction-app-postgresql/transaction-appdb"
            DATABASE_REPLICA_URL: "postgres://postgres:postgres@transaction-app-postgresql/transaction-appdb" 
            DEBUG_EMAIL: $(DEBUG_EMAIL)
        networks:
            default:
                aliases:
                    - www.local.com.ar
                    - www.local.com
        ports:
            - "8000:8000"
            - "8888:8888"
        volumes:
            - ./src:/app
        depends_on:
            - transaction-app-postgresql
        stdin_open: true
        tty: true

networks:
    default:
        name: transaction-app-network
